### ISSUE TITLE
錯誤處理

### ISSUE THREAD

**Issue by azole** [a07401234/nodejs-MFEE16#1]
https://github.com/a07401234/nodejs-MFEE16/blob/8c0b29662f161e3f30bee22b626edcb6c53b83fc/crawler/readfile-promise.js#L45

這裡會 catch 到的錯誤，可能是讀檔錯誤，也有可能是 axios.get 這個 promise 拋出來的錯誤喔。

**Comment by a07401234** [comment]
已修正，謝謝老師
